name       : solarus
version    : 1.5.3
release    : 5
source     :
    - https://github.com/solarus-games/solarus/archive/v1.5.3.tar.gz : 5930584e7c333089a2c1bf372ccc25ad3fb5c1d973189d2bf67f2308189af94d
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0
component  : programming
summary    : Solarus is an open-source Zelda-like 2D game engine written in C++.
description: |
    Solarus is an open-source Zelda-like 2D game engine written in C++.
libsplit   : no
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
    - physfs-devel
setup      : |
    %cmake -DSOLARUS_USE_LUAJIT=1 .
build      : |
    %make
install    : |
    %make_install
