name       : solarus
version    : 1.6.0
release    : 8
source     :
    - https://gitlab.com/solarus-games/solarus/-/archive/v1.6.0/solarus-v1.6.0.tar.gz : e1cdb686674607fc7ce84c7ffb1811bc441a92b0948dc6de09ae5d283e89629d
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : programming
summary    : Solarus is an open-source Zelda-like 2D game engine written in C++.
description: |
    Solarus is an open-source Zelda-like 2D game engine written in C++.
libsplit   : no
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
    - physfs-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-desktop.patch
    %cmake_ninja -DSOLARUS_USE_LUAJIT=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
