name       : solarus
version    : 1.5.0
release    : 2
source     :
    - https://github.com/christopho/solarus/archive/v1.5.0.tar.gz : 23ef0a92e0b924af7c474bbb2c691a213d953a9a0016d5de443f5d50367718d0
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0
component  : programming
summary    : Solarus is an open-source Zelda-like 2D game engine written in C++.
description: |
    Solarus is an open-source Zelda-like 2D game engine written in C++.
libsplit   : no
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(ogg)
    - pkgconfig(openal)
    - pkgconfig(Qt5Help)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
    - physfs-devel
setup      : |
    %cmake -DSOLARUS_USE_LUAJIT=1 .
build      : |
    %make
install    : |
    %make_install
