name       : solarus
version    : 1.6.4
release    : 10
source     :
    - https://gitlab.com/solarus-games/solarus/-/archive/v1.6.4/solarus-v1.6.4.tar.bz2 : b2e00a7df8953903ba022a8f392038e86f675cee714da19cf9a5f8535c42f349
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : programming
summary    : Solarus is an open-source Zelda-like 2D game engine written in C++
description: |
    Solarus is an open-source Zelda-like 2D game engine written in C++.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(glm)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(vorbis)
setup      : |
    %cmake_ninja -DSOLARUS_USE_LUAJIT=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
