name       : solarus
version    : 1.6.5
release    : 13
source     :
    - https://gitlab.com/solarus-games/solarus/-/archive/v1.6.5/solarus-v1.6.5.tar.bz2 : 4b4ac59df8ab63ee2e305cbf48118d6be0cf9665968eb0b06dd1acdf4346516f
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : programming
summary    : Solarus is an open-source Zelda-like 2D game engine written in C++
description: |
    Solarus is an open-source Zelda-like 2D game engine written in C++.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(glm)
    - pkgconfig(libmodplug)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(vorbis)
setup      : |
    %cmake_ninja -DSOLARUS_USE_LUAJIT=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
